interface Inputs  {
    name: String,
    lastName: string,
    secondLastName: string,
    nif: string,
    email: string,
    phone: string,
    emergencyContact: string,
    emergencyPhone: string,
    hotelName: string,
    bus: string,
    matricula: string,
    country: string,
    city: string,
    arrivalDate: Date,
    departureDate: Date,
    celiac: string,
    vegetarian: string,
};