import Link from 'next/link'
import '../../globals.css'
import TabsComponent from '../../components/TabsComponent'
import { Toaster } from 'react-hot-toast'
import { LinkInfo } from '@/utils/types/inputTypes'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const links: LinkInfo[] = [
    {
      href: "/admin/users",
      name: "Gestion de usuarios"
    },
    {
      href: "/admin/events",
      name: "Eventos"
    },
    {
      href: "/admin/countries",
      name: "Paises"
    },
  ]


  return (
    <>
      <div>
        <nav>
          <TabsComponent links={links} />
        </nav>
        {children}
      </div>
    </>
  )
}