import Link from 'next/link'
import '../globals.css'
import { Inter } from 'next/font/google'
import TabsContainer from '../components/TabsContainer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function EstadisticasLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <>
      <div>
        <nav>
          <TabsContainer />
        </nav>
        {children}
      </div>
    </>
  )
}