import './globals.css'
import { Inter } from 'next/font/google'
import MainNavigation from './components/MainNavigation'
import AuthProvider from './context/AuthProvider'
import { Toaster } from 'react-hot-toast'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <AuthProvider>
        <body >
          <Toaster position="top-right" />
          <MainNavigation />
          {children}
        </body>
      </AuthProvider>
    </html>
  )
}
