import './globals.css'
import { Inter } from 'next/font/google'
import MainNavigation from './components/MainNavigation'
import AuthProvider from './context/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <AuthProvider>
          <body >
            <MainNavigation />
            {children}
          </body>
      </AuthProvider>
    </html>
  )
}
